

//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace BEUBIO
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

using System.Data.Entity.Core.Objects;
using System.Linq;


public partial class Entities_Bio : DbContext
{
    public Entities_Bio()
        : base("name=Entities_Bio")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<Articulo> Articuloes { get; set; }

    public virtual DbSet<Negocio> Negocios { get; set; }

    public virtual DbSet<Usuario> Usuarios { get; set; }

    public virtual DbSet<Venta> Ventas { get; set; }


    public virtual ObjectResult<rptArticulosMasComprados_Result> rptArticulosMasComprados(Nullable<int> id)
    {

        var idParameter = id.HasValue ?
            new ObjectParameter("id", id) :
            new ObjectParameter("id", typeof(int));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<rptArticulosMasComprados_Result>("rptArticulosMasComprados", idParameter);
    }


    public virtual ObjectResult<rptStockArticulos_Result> rptStockArticulos(Nullable<int> id)
    {

        var idParameter = id.HasValue ?
            new ObjectParameter("id", id) :
            new ObjectParameter("id", typeof(int));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<rptStockArticulos_Result>("rptStockArticulos", idParameter);
    }


    public virtual ObjectResult<rptStockArticulosUsuarios_Result> rptStockArticulosUsuarios()
    {

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<rptStockArticulosUsuarios_Result>("rptStockArticulosUsuarios");
    }


    public virtual ObjectResult<rtpStockUsuarios_Result> rtpStockUsuarios()
    {

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<rtpStockUsuarios_Result>("rtpStockUsuarios");
    }


    public virtual ObjectResult<rptComprasUsuarioCategoria_Result> rptComprasUsuarioCategoria()
    {

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<rptComprasUsuarioCategoria_Result>("rptComprasUsuarioCategoria");
    }


    public virtual ObjectResult<rptComprasUsuarioCategoria_id_Result> rptComprasUsuarioCategoria_id(Nullable<int> id)
    {

        var idParameter = id.HasValue ?
            new ObjectParameter("id", id) :
            new ObjectParameter("id", typeof(int));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<rptComprasUsuarioCategoria_id_Result>("rptComprasUsuarioCategoria_id", idParameter);
    }


    public virtual ObjectResult<rptCompraUsuarios_Result> rptCompraUsuarios()
    {

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<rptCompraUsuarios_Result>("rptCompraUsuarios");
    }


    public virtual ObjectResult<rptStockUnidadArticulosCategorias_Result> rptStockUnidadArticulosCategorias()
    {

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<rptStockUnidadArticulosCategorias_Result>("rptStockUnidadArticulosCategorias");
    }


    public virtual ObjectResult<rptStockUnidadArticulosCategorias_ID_Result> rptStockUnidadArticulosCategorias_ID(Nullable<int> id)
    {

        var idParameter = id.HasValue ?
            new ObjectParameter("id", id) :
            new ObjectParameter("id", typeof(int));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<rptStockUnidadArticulosCategorias_ID_Result>("rptStockUnidadArticulosCategorias_ID", idParameter);
    }


    public virtual ObjectResult<rptStocProductoUsuarios_Result> rptStocProductoUsuarios()
    {

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<rptStocProductoUsuarios_Result>("rptStocProductoUsuarios");
    }


    public virtual ObjectResult<rptStocProductoUsuariosID_Result> rptStocProductoUsuariosID(Nullable<int> id)
    {

        var idParameter = id.HasValue ?
            new ObjectParameter("id", id) :
            new ObjectParameter("id", typeof(int));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<rptStocProductoUsuariosID_Result>("rptStocProductoUsuariosID", idParameter);
    }


    public virtual ObjectResult<rptPrueba_1_Result> rptPrueba_1(Nullable<int> id)
    {

        var idParameter = id.HasValue ?
            new ObjectParameter("id", id) :
            new ObjectParameter("id", typeof(int));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<rptPrueba_1_Result>("rptPrueba_1", idParameter);
    }

}

}

